// API Service
export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_RESPONSE = 'RECEIVE_RESPONSE';

// Dialog Actions
export const TOGGLE_TASK_CREATOR = 'TOGGLE_TASK_CREATOR';
export const TOGGLE_TASK_EDITOR = 'TOGGLE_TASK_EDITOR';
export const TOGGLE_STEP_CREATOR = 'TOGGLE_STEP_CREATOR';
export const TOGGLE_INVITATION = 'TOGGLE_INVITATION';
export const TOGGLE_DELETE_TASK = 'TOGGLE_DELETE_TASK';
export const TOGGLE_QUIT_TASK = 'TOGGLE_QUIT_TASK';
export const TOGGLE_STEP_VIEWER = 'TOGGLE_STEP_VIEWER';
export const TOGGLE_TASK_VIEWER = 'TOGGLE_TASK_VIEWER';
export const TOGGLE_STEP_EDITOR = 'TOGGLE_STEP_EDITOR';
export const TOGGLE_TASK_CLONER = 'TOGGLE_TASK_CLONER';
export const TOGGLE_TASK_APP_CREATOR = 'TOGGLE_TASK_APP_CREATOR';
export const TOGGLE_TASK_APP_PREVIEW = 'TOGGLE_TASK_APP_PREVIEW';
export const TOGGLE_MINI_APP_PASSWORD = 'TOGGLE_MINI_APP_PASSWORD';

// Task Actions
export const UPDATE_TASK_INFO = 'UPDATE_TASK_INFO';
export const RESET_TASK_INFO = 'RESET_TASK_INFO';
export const TOGGLE_TASK_ACTION_PENDING = 'TOGGLE_TASK_ACTION_PENDING';
export const TOGGLE_TASK_CREATE_PENDING = 'TOGGLE_TASK_CREATE_PENDING';
export const TOGGLE_TASK_DELETE_PENDING = 'TOGGLE_TASK_DELETE_PENDING';
export const TOGGLE_TASK_SAVE_PENDING = 'TOGGLE_TASK_SAVE_PENDING';
export const TOGGLE_TASK_QUIT_PENDING = 'TOGGLE_TASK_QUIT_PENDING';
export const TOGGLE_TASK_INVITATION_STATUS_PENDING = 'TOGGLE_TASK_INVITATION_STATUS_PENDING';
export const TOGGLE_TASK_CLONE_PENDING = 'TOGGLE_TASK_CLONE_PENDING';

// Step Actions
export const UPDATE_STEP_INFO = 'UPDATE_STEP_INFO';
export const RESET_STEP_INFO = 'RESET_STEP_INFO';
export const SET_ACTIVE_TASK_ID = 'SET_ACTIVE_TASK_ID';
export const TOGGLE_TRIGGER_PENDING = 'TOGGLE_TRIGGER_PENDING';
export const SET_IS_START_END = 'SET_IS_START_END';

// Snackbar Actions
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';

// Currentuser Actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const RESET_EDIT_MODE = 'RESET_EDIT_MODE';

// TaskUsers Actions
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_SUPER_ROLE = 'SET_USER_SUPER_ROLE';
export const REMOVE_USER = 'REMOVE_USER';

// Graph Actions
export const SET_DRAGGING_NODE_TYPE = 'SET_DRAGGING_NODE_TYPE';
export const SET_NODE_CANVAS_COORD = 'SET_NODE_CANVAS_COORD';
export const TOGGLE_ADD_EDGE_BUTTON = 'TOGGLE_ADD_EDGE_BUTTON';
export const SET_GRAPH_DATA_ORIGIN = 'SET_GRAPH_DATA_ORIGIN';
export const UPDATE_GRAPH_DATA_JSON = 'UPDATE_GRAPH_DATA_JSON';
export const TOGGLE_DELETE_BUTTON = 'TOGGLE_DELETE_BUTTON';
export const OPEN_NODE_DESCRIPTION_BOX = 'OPEN_NODE_DESCRIPTION_BOX';
export const CLOSE_NODE_DESCRIPTION_BOX = 'CLOSE_NODE_DESCRIPTION_BOX';
export const UPDATE_NODE_INFO = 'UPDATE_NODE_INFO';

// Filter Actions
export const SET_FILTER = 'SET_FILTER';

// TaskApp Actions
export const TOGGLE_IS_CREATOR = 'TOGGLE_IS_CREATOR';
export const RESET_LATEST_DOWNLOAD_TID = 'RESET_LATEST_DOWNLOAD_TID';

// Mini App Actions
export const UPDATE_AID = 'UPDATE_AID';
export const UPDATE_MINI_APP_KEY = 'UPDATE_MINI_APP_KEY';

// Step Component Actions
export const UPDATE_COMPONENT_INFO = 'UPDATE_COMPONENT_INFO';
export const COMPONENT_FETCHED = 'COMPONENT_FETCHED';
