// API Service
export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_RESPONSE = 'RECEIVE_RESPONSE';

// Dialog Actions
export const TOGGLE_TASK_CREATOR = 'TOGGLE_TASK_CREATOR';
export const TOGGLE_TASK_EDITOR = 'TOGGLE_TASK_EDITOR';
export const TOGGLE_STEP_CREATOR = 'TOGGLE_STEP_CREATOR';
export const TOGGLE_INVITATION = 'TOGGLE_INVITATION';
export const TOGGLE_DELETE_TASK = 'TOGGLE_DELETE_TASK';

// Task Actions
export const UPDATE_TASK_INFO = 'UPDATE_TASK_INFO';
export const RESET_TASK_INFO = 'RESET_TASK_INFO';
export const TOGGLE_TASK_ACTION_PENDING = 'TOGGLE_TASK_ACTION_PENDING';

// Step Actions
export const UPDATE_STEP_INFO = 'UPDATE_STEP_INFO';
export const RESET_STEP_INFO = 'RESET_STEP_INFO';
export const SET_ACTIVE_TASK_ID = 'SET_ACTIVE_TASK_ID';

// Snackbar Actions
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';

// Currentuser Actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Graph Actions
export const SET_DRAGGING_INDEX = 'SET_DRAGGING_INDEX';
